# Generated by Django 2.1.7 on 2019-03-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=30)),
                ('No_of_students', models.IntegerField()),
                ('class_description', models.CharField(max_length=2000)),
                ('class_picture', models.ImageField(blank=True, upload_to='', verbose_name='photos/%Y/%m/%d/')),
                ('class_coordinators', models.CharField(max_length=30)),
                ('monthly_fee', models.IntegerField()),
                ('available_seats', models.IntegerField()),
                ('class_schedule', models.CharField(max_length=30)),
                ('class_coordinators_phone_no', models.IntegerField()),
                ('subjects_name', models.CharField(max_length=1000)),
            ],
        ),
    ]
