# Generated by Django 2.1.7 on 2019-03-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='students_id',
            field=models.IntegerField(),
        ),
    ]
